// react-chat/src/components/MessageInput.tsx
import React, { useState, FormEvent } from "react";

interface MessageInputProps {
  onSendMessage: (message: string) => void;
  disabled: boolean;
}

export const MessageInput: React.FC<MessageInputProps> = ({
  onSendMessage,
  disabled,
}) => {
  const [message, setMessage] = useState("");

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (message.trim() && !disabled) {
      onSendMessage(message.trim());
      setMessage("");
    }
  };

  return (
    <form onSubmit={handleSubmit} style={{ display: "flex", gap: "10px" }}>
      <input
        type="text"
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        placeholder="Escribe un mensaje..."
        disabled={disabled}
        style={{
          flex: 1,
          padding: "10px",
          border: "1px solid #ddd",
          borderRadius: "4px",
          fontSize: "14px",
          outline: "none",
        }}
      />
      <button
        type="submit"
        disabled={disabled || !message.trim()}
        style={{
          padding: "10px 20px",
          backgroundColor: disabled || !message.trim() ? "#ccc" : "#007bff",
          color: "white",
          border: "none",
          borderRadius: "4px",
          cursor: disabled || !message.trim() ? "not-allowed" : "pointer",
          fontWeight: "bold",
        }}
      >
        Enviar
      </button>
    </form>
  );
};

// vue-chat/src/components/MessageInput.vue
<template>
  <form @submit.prevent="handleSubmit" class="message-input-form">
    <input
      v-model="message"
      type="text"
      placeholder="Escribe un mensaje..."
      :disabled="disabled"
      class="message-input"
    />
    <button
      type="submit"
      :disabled="disabled || !message.trim()"
      class="send-button"
      :class="{ disabled: disabled || !message.trim() }"
    >
      Enviar
    </button>
  </form>
</template>

<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
  disabled: boolean;
}>();

const emit = defineEmits<{
  sendMessage: [message: string];
}>();

const message = ref("");

const handleSubmit = () => {
  if (message.value.trim() && !props.disabled) {
    emit("sendMessage", message.value.trim());
    message.value = "";
  }
};
</script>

<style scoped>
.message-input-form {
  display: flex;
  gap: 10px;
}

.message-input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  outline: none;
}

.message-input:focus {
  border-color: #42b883;
}

.send-button {
  padding: 10px 20px;
  background-color: #42b883;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: bold;
  transition: background-color 0.2s;
}

.send-button:hover:not(.disabled) {
  background-color: #359268;
}

.send-button.disabled {
  background-color: #ccc;
  cursor: not-allowed;
}
</style>
